version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=development
      - ODOO_HOST=odoo
      - ODOO_PORT=5432
      - ODOO_DB_NAME=odoo
      - ODOO_DB_USER=odoo
      - ODOO_DB_PASSWORD=odoo
      - ODOO_URL=http://odoo:8069
      - REDIS_HOST=redis
    depends_on:
      - redis
      - odoo

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  odoo:
    image: odoo:16.0
    ports:
      - "8069:8069"
    environment:
      - HOST=odoo
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./odoo/config:/etc/odoo
      - ./odoo/addons:/mnt/extra-addons

volumes:
  odoo-web-data: