server:
  port: "8080"
  baseURL: "http://localhost:8080"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "your-password"
  dbname: "ecommerce"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"

odoo:
  url: "http://localhost:8069"
  database: "odoo"
  username: "admin"
  password: "admin"

adyen:
  apiKey: "your-api-key"
  environment: "test"
  merchantID: "your-merchant-id"