server:
  port: "8080"
  baseURL: "http://localhost:8080"

database:
  host: "db"
  port: "5432"
  user: "odoo"
  password: "odoo"
  dbname: "postgres"  # Use postgres as initial database

redis:
  host: "redis"
  port: "6379"
  password: ""
  db: 0

rabbitmq:
  url: "amqp://guest:guest@rabbitmq:5672/"

odoo:
  url: "http://odoo:8069"
  database: "odoo"  # This will be the name of the database you create
  username: "admin"
  password: "admin"

adyen:
  apiKey: "your-api-key"
  environment: "test"